### ISSUE TITLE
user.sh error

### ISSUE THREAD

**Issue by josn0** [gejanssen/install#1]
In 'user.sh', on lines 17&18, output redirection is done outside of 'sudo', so writing to /etc/sudoers is would not work. Suggestion:
`sudo bash -c "echo 'gej	ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers"`
or:
`echo 'gej	ALL=(ALL) NOPASSWD: ALL' | sudo tee -a /etc/sudoers > /dev/null`
This is obviously especially important for the next line (18). (this is an insider joke..)

**Comment by gejanssen** [comment]
resolved, see the updated version.

**Comment by gejanssen** [comment]
Used the tee example as you advised.
